const lessons = [
[1,1,"Course Introduction & IS Updates","Week01_Session01_IS_Updates_Course_Intro.html",1],[1,2,"Digital Transformation Deep Dive","Week01_Session02_Digital_Transformation_Deep_Dive.html",1],[2,1,"Platform Business & IS Trends","Week02_Session01_Platform_Business_IS_Trends.html",1],[2,2,"IS Trends 2024–2025","Week02_Session02_IS_Trends_2024_2025.html",1],[3,1,"IS in Philippine Organizations","Week03_Session01_IS_Philippine_Organizations.html",1],[3,2,"Technology Evaluation Frameworks","Week03_Session02_Technology_Evaluation_Frameworks.html",1],[4,1,"Professional Technology Briefs","Week04_Session01_Professional_Technology_Briefs.html",1],[4,2,"Module 1 Review & Exam 1","Week04_Session02_Module1_Review_and_Exam1.html",1],
[5,1,"Cloud Computing Foundations","Week05_Session01_Cloud_Computing_Foundations.html",2],[5,2,"SaaS Platforms & Cloud Accounting","Week05_Session02_SaaS_Platforms_Cloud_Accounting.html",2],[6,1,"APIs & Systems Integration","Week06_Session01_APIs_Systems_Integration.html",2],[6,2,"Low-Code Workflow Automation","Week06_Session02_Low_Code_Workflow_Automation.html",2],[7,1,"RPA & Accounting Automation","Week07_Session01_RPA_Accounting_Automation.html",2],[7,2,"Workflow Orchestration & Governance","Week07_Session02_Workflow_Orchestration_Governance.html",2],[8,1,"Process Automation Proposal Workshop","Week08_Session01_Process_Automation_Proposal_Workshop.html",2],[8,2,"Module 2 Integration Lab","Week08_Session02_Module2_Integration_Lab.html",2],
[9,1,"Business Intelligence & Data Foundations","Week09_Session01_Business_Intelligence_Data_Foundations.html",3],[9,2,"Data Visualization & Dashboard Design","Week09_Session02_Data_Visualization_Dashboard_Design.html",3],[10,1,"AI & Machine Learning for Accountants","Week10_Session01_AI_Machine_Learning_Accountants.html",3],[10,2,"Data Governance & Analytics Interpretation","Week10_Session02_Data_Governance_Analytics_Interpretation.html",3],[11,1,"Decision Support & Predictive Analytics","Week11_Session01_Decision_Support_Predictive_Analytics.html",3],[11,2,"Analytics Output Workshop","Week11_Session02_Analytics_Output_Workshop.html",3],[12,1,"Module 3 Review","Week12_Session01_Module3_Review.html",3],[12,2,"Module 3 Exam","Week12_Session02_Module3_Exam.html",3],
[13,1,"Cybersecurity Foundations","Week13_Session01_Cybersecurity_Foundations.html",4],[13,2,"Cybersecurity Threats & Attack Scenarios","Week13_Session02_Cybersecurity_Threats_Attack_Scenarios.html",4],[14,1,"Data Privacy & Philippine Compliance","Week14_Session01_Data_Privacy_Philippine_Compliance.html",4],[14,2,"IT Governance & Risk Management","Week14_Session02_IT_Governance_Risk_Management.html",4],[15,1,"IT Risk, Internal Controls & Audit","Week15_Session01_IT_Risk_Internal_Controls_Audit.html",4],[15,2,"Module 4 Review & Assessment Preparation","Week15_Session02_Module4_Review_Assessment_Preparation.html",4],
[16,1,"Module 4 Assessment & Project Transition","Week16_Session01_Module4_Assessment_Project_Transition.html",5],[16,2,"FinTech, Blockchain & Mobile Systems","Week16_Session02_FinTech_Blockchain_Mobile_Systems.html",5],[17,1,"IoT & Sustainable Information Systems","Week17_Session01_IoT_Sustainable_Information_Systems.html",5],[17,2,"Change Management & User Adoption","Week17_Session02_Change_Management_User_Adoption.html",5],[18,1,"Final IS Update Proposal Lab","Week18_Session01_Final_IS_Update_Proposal_Lab.html",5],[18,2,"Final IS Update Proposal Defense","Week18_Session02_Final_IS_Update_Proposal_Defense.html",5]
];
const blocks = [[1,"Foundations & Emerging Trends","Weeks 1–4"],[2,"Cloud, Integration & Automation","Weeks 5–8"],[3,"Data, Analytics & AI","Weeks 9–12"],[4,"Security, Privacy & Governance","Weeks 13–15"],[5,"Future Systems & Final Project","Weeks 16–18"]];
const el = id => document.getElementById(id);
const library=el("library"),siteHeader=el("siteHeader"),siteFooter=el("siteFooter"),viewer=el("viewer"),modules=el("modules"),lessonFrame=el("lessonFrame"),frameShell=el("frameShell");
let completed=Math.min(Math.max(Number(localStorage.getItem("profel2-completed"))||Number(localStorage.getItem("profel2-read-count"))||0,0),lessons.length);
let activeIndex=0;
function save(){localStorage.setItem("profel2-completed",String(completed));localStorage.setItem("profel2-read-count",String(completed));}
function progress(){const pct=Math.round(completed/lessons.length*100);el("headerProgress").textContent=`${pct}%`;el("completedCount").textContent=completed;el("progressText").textContent=`${completed} of ${lessons.length} sessions completed`;el("miniProgress").style.width=`${pct}%`;el("resetProgress").hidden=completed===0;const next=Math.min(completed,lessons.length-1),l=lessons[next];el("continueBtn").textContent=completed===0?"Start Week 1 · Session 1":completed===lessons.length?"Review final session":`Continue Week ${l[0]} · Session ${l[1]}`;}
function cardHTML(l,i){const locked=i>completed,done=i<completed,current=i===completed&&completed<lessons.length;const status=locked?"Locked":done?"Completed":current?"Current":"Available";return `<button class="lesson-card ${done?"completed":""}" data-index="${i}" ${locked?"disabled":""}><div><div class="lesson-top"><span class="session-tag">SESSION ${l[1]}</span><span class="status-pill">${locked?"🔒 ":done?"✓ ":""}${status}</span></div><h4>${l[2]}</h4></div><div class="lesson-open"><span>${locked?"Complete the previous session":done?"Open again":"Open presentation"}</span><span>${locked?"":"→"}</span></div></button>`;}
function render(){progress();modules.innerHTML=blocks.map(b=>{const grouped=lessons.map((l,i)=>({l,i})).filter(x=>x.l[4]===b[0]);const weeks=[...new Set(grouped.map(x=>x.l[0]))];return `<section class="module"><div class="module-head"><span class="module-number">0${b[0]}</span><div><h3>${b[1]}</h3><p>${b[2]}</p></div><small>${grouped.length} sessions</small></div><div class="week-list">${weeks.map(w=>{const pair=grouped.filter(x=>x.l[0]===w);return `<div class="week-row"><div class="week-label"><small>WEEK</small><strong>${String(w).padStart(2,"0")}</strong></div>${pair.map(x=>cardHTML(x.l,x.i)).join("")}</div>`}).join("")}</div></section>`}).join("");modules.querySelectorAll(".lesson-card:not(:disabled)").forEach(btn=>btn.addEventListener("click",()=>openLesson(Number(btn.dataset.index))));}
function openLesson(i){activeIndex=i;const l=lessons[i];library.hidden=true;siteHeader.hidden=true;siteFooter.hidden=true;viewer.hidden=false;el("viewerMeta").textContent=`Week ${l[0]} · Session ${l[1]}`;el("viewerTitle").textContent=l[2];lessonFrame.src=`lessons/${l[3]}`;el("prevBtn").disabled=i===0;el("nextBtn").disabled=i===lessons.length-1||i>=completed;el("completeBtn").textContent=i<completed?"✓ Completed · Continue":i===lessons.length-1?"Mark as Completed ✓":"Mark as Completed →";window.scrollTo(0,0);}
function closeViewer(){viewer.hidden=true;library.hidden=false;siteHeader.hidden=false;siteFooter.hidden=false;lessonFrame.src="about:blank";render();location.hash="lessons";}
el("continueBtn").addEventListener("click",()=>openLesson(completed>=lessons.length?lessons.length-1:completed));
el("backBtn").addEventListener("click",closeViewer);
el("prevBtn").addEventListener("click",()=>{if(activeIndex>0)openLesson(activeIndex-1)});
el("nextBtn").addEventListener("click",()=>{if(activeIndex<lessons.length-1&&activeIndex<completed)openLesson(activeIndex+1)});
el("completeBtn").addEventListener("click",()=>{if(activeIndex>=completed){completed=Math.max(completed,activeIndex+1);save();}if(activeIndex<lessons.length-1)openLesson(activeIndex+1);else closeViewer();});
el("resetProgress").addEventListener("click",()=>{if(confirm("Reset all PROFEL 2 lesson progress?")){completed=0;save();render();}});
el("presentBtn").addEventListener("click",async()=>{try{if(frameShell.requestFullscreen)await frameShell.requestFullscreen();}catch(e){window.open(lessonFrame.src,"_blank","noopener");}});
el("exitFullscreen").addEventListener("click",()=>document.exitFullscreen&&document.exitFullscreen());
document.addEventListener("fullscreenchange",()=>{el("exitFullscreen").hidden=!document.fullscreenElement;});
document.addEventListener("keydown",e=>{if(viewer.hidden)return;if(e.key==="Escape"&&!document.fullscreenElement)closeViewer();if(e.key==="ArrowLeft"&&!el("prevBtn").disabled)el("prevBtn").click();if(e.key==="ArrowRight"&&!el("nextBtn").disabled)el("nextBtn").click();});
render();
